workflows:
  android-build:
    name: Android Build
    instance_type: linux_x2
    max_build_duration: 120
    environment:
      node: 18
      java: 11
    triggering:
      events:
        - push
        - pull_request
      branch:
        include:
          - main
    scripts:
      - name: Install dependencies
        script: |
          npm install -g pnpm
          pnpm install
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
      - android/app/build/outputs/bundle/release/**/*.aab

  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      node: 18
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
      branch:
        include:
          - main
    scripts:
      - name: Install dependencies
        script: |
          npm install -g pnpm
          pnpm install
      - name: Install pods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          xcodebuild -workspace ios/neuromodulation_mapper.xcworkspace \
            -scheme neuromodulation_mapper \
            -configuration Release \
            -derivedDataPath build \
            -arch arm64 \
            build
    artifacts:
      - build/Build/Products/Release-iphoneos/**/*.app
